option renaming and upgrades
jasp-stats/jaspMetaAnalysis pull request #137
Opened 2022-08-29 13:44 UTC by sophieberkhout

Classical and Bayesian meta-analysis ([#2019](https://github.com/jasp-stats/INTERNAL-jasp/issues/2019), [#2014](https://github.com/jasp-stats/INTERNAL-jasp/issues/2014)).

I did not rename options with `visible:		module == "cochrane"`, because I assume that would break things in the cochrane module. @FBartos not sure if other options being renamed is a problem for that module.

2022-08-29 14:30 UTC, sophieberkhout commented
Oops forgot to update tests.. one sec.

2022-08-30 10:21 UTC, sophieberkhout commented
So the remaining problem with the unit tests (only for macOS) seems to be with the robust meta-analysis which I made no changes to.

I think this is the problem:
> fatal error: /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /usr/local/libexec/jags-terminal (No such file or directory)

@boutinb you mentioned in the slack something about not finding the jags package. Could this be related?

2022-09-14 13:56 UTC, Kucharssim requested changes
Looks quite good, just a couple of minor comments.

> I did not rename options with visible: module == "cochrane", because I assume that would break things in the cochrane module. @FBartos not sure if other options being renamed is a problem for that module.

That should not be a problem for that module as currently `jaspCochrane` does not source the QML files directly but relies on copies of the original files from here, so you should not be able to break anything. So it would make more sense to do the changes here and the renaming in the Cochrane module would be done just by @FBartos sourcing the files directly and copying the relevant sections for the Upgrader once this PR is merged..

2022-09-14 13:56 UTC, Kucharssim commented on inst/Upgrades.qml
> +        // ClassicalMetaAnalysis.qml
could you replace spaces with tabs in the qml files please?

2022-09-14 13:56 UTC, Kucharssim commented on inst/Upgrades.qml
> +		fromVersion:	"0.15"
given we'll merge this after this release, you can change it to `fromVersion: "0.16.4"` and `toVersion: "0.17"`

2022-09-14 13:56 UTC, Kucharssim commented on inst/qml/qml_components/BayesianMetaAnalysisPriors.qml
> +					name: 			"normalStd"
```suggestion
					name: 			"normalSd"
```

2022-10-14 11:25 UTC, Kucharssim commented
Could you [rebase](https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/development/git-guide.md#rebasing-your-repository-github-documentation-rebasing) your branch and resolve the conflicts? Let me know if you have any help with that!

2022-10-18 12:21 UTC, closed without merging