Add seed option to Bayesian meta-analysis
jasp-stats/jaspMetaAnalysis pull request #77
Opened 2021-09-30 14:51 UTC by sophieberkhout

Requested by @FBartos as he got questions about this.

The `meta_bma` function apparently requires to use the `set.seed` function instead of a seed argument, as it passes the seed to rstan internally.

2021-09-30 15:12 UTC, sophieberkhout commented
Would it now also be possible to not skip the unit tests anymore?

2021-09-30 18:52 UTC, FBartos requested changes

2021-09-30 18:52 UTC, FBartos commented on inst/qml/qml_components/BayesianMetaAnalysisAdvanced.qml
> +
I think that it doesn't need to be in a group of its own.

2021-09-30 18:52 UTC, FBartos commented on R/bayesianmetaanalysiscommon.R
> +  .setSeedJASP(options)
it might be better to put it right before the fitting function, in case that the order of flow changes / there are other rng elements

2021-09-30 18:53 UTC, FBartos commented
Yes, I think that having the unit tests, at least for one OS would be great

2021-10-01 10:10 UTC, FBartos commented
@vandenman , do you think that this could be considered a bug fix and we could merge it in if we restrict the OS-specific unit tests to windows?

2021-10-01 10:15 UTC, sophieberkhout commented
I added an if statement now so the unit tests only run if the system is Windows. Let's see if it works :)

2021-10-01 10:17 UTC, FBartos commented
if so, maybe changing the if statement to ``testthat::skip_on_os(c("mac", "linux", "solaris"))`` might be preferable

2021-10-01 10:26 UTC, sophieberkhout commented
Okay they pass so I'll change it `skip_on_os`

2021-10-01 10:55 UTC, FBartos approved these changes
I'm not sure whether we can still merge this in though.

2021-10-01 10:59 UTC, vandenman commented
hmmm, there's not really an issue this fixes right? It's also not really an ideal fix, because this
```r
testthat::skip_on_os(c("mac", "linux", "solaris"))
```
means that this analysis should only be touched by people working on Windows (as people on macOS and Linux can never update the unit tests).

I'd be in favor of postponing this, assuming we can find a better solution.

2021-10-01 11:11 UTC, FBartos commented
The issue was a lack of reproducibility when performing Bayesian meta-analysis.

> means that this analysis should only be touched by people working on Windows (as people on macOS and Linux can never update the unit tests).

I guess that till Stan fixes the samplers rng across OSes our hands are tied. Isn't this still an upgrade for the unit tests since there were no unit tests for the numerical results before (i.e., they were skipped on all OSes)? 

Maybe an alternative could be adding dispatching of the unit tests for multiple OSes, but that would make their updating even more painful.

It would be a nice thing to have since several people asked for it on a workshop but we can postpone it.

2021-10-01 11:19 UTC, vandenman commented
> I guess that till Stan fixes the samplers rng across OSes our hands are tied.

From https://mc-stan.org/docs/2_27/reference-manual/reproducibility-chapter.html

![image](https://user-images.githubusercontent.com/21319932/135610958-95f11b57-1cd9-47a2-8788-903f9e3775cb.png)

So I don't think they will ever fix this (it's not even seen as an issue in their eyes).

> Isn't this still an upgrade for the unit tests since there were no unit tests for the numerical results before (i.e., they were skipped on all OSes)?

After the first time someone else works on this code, I think that these tests will just be skipped again.

> It would be a nice thing to have since several people asked for it on a workshop but we can postpone it.

I agree it is an upgrade, but I'm just not too fond of the unit tests. We could also just merge this and then see how long it takes before somebody feels the need to skip the tests. If we go that way, we might want to leave a comment in the unit test code to skip the tests if they start failing.

2021-10-01 11:53 UTC, FBartos commented
hmm, what do you suggest as the best way forward then? 

Adding a comment to the unit tests and merging it in?

2021-10-01 12:28 UTC, vandenman commented
> Adding a comment to the unit tests and merging it in?

At least a comment, so that the next person knows they can ignore the tests if they start failing.

2021-10-01 12:50 UTC, vandenman approved these changes
Feel free to merge this once the tests pass!

2021-10-01 12:51 UTC, FBartos commented
Thanks Don!

2021-10-01 12:52 UTC, merged